package com.cosettur.models.pojos;
// Generated 25/09/2018 11:20:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoRuta generated by hbm2java
 */
public class CatalogoRuta  implements java.io.Serializable {


     private Short idRuta;
     private String ruta;
     private Set fichaInscripcions = new HashSet(0);

    public CatalogoRuta() {
    }

	
    public CatalogoRuta(String ruta) {
        this.ruta = ruta;
    }
    public CatalogoRuta(String ruta, Set fichaInscripcions) {
       this.ruta = ruta;
       this.fichaInscripcions = fichaInscripcions;
    }
   
    public Short getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Short idRuta) {
        this.idRuta = idRuta;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set getFichaInscripcions() {
        return this.fichaInscripcions;
    }
    
    public void setFichaInscripcions(Set fichaInscripcions) {
        this.fichaInscripcions = fichaInscripcions;
    }




}


