package com.cosettur.models.pojos;
// Generated 25/09/2018 11:20:59 PM by Hibernate Tools 4.3.1



/**
 * CatalogoDias generated by hbm2java
 */
public class CatalogoDias  implements java.io.Serializable {


     private byte idDia;
     private String dia;

    public CatalogoDias() {
    }

    public CatalogoDias(byte idDia, String dia) {
       this.idDia = idDia;
       this.dia = dia;
    }
   
    public byte getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(byte idDia) {
        this.idDia = idDia;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }




}


