package com.cosettur.models.pojos;
// Generated 25/09/2018 11:20:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoModalidad generated by hbm2java
 */
public class CatalogoModalidad  implements java.io.Serializable {


     private Byte idModalidad;
     private String modalidad;
     private Set fichaInscripcions = new HashSet(0);

    public CatalogoModalidad() {
    }

    public CatalogoModalidad(String modalidad, Set fichaInscripcions) {
       this.modalidad = modalidad;
       this.fichaInscripcions = fichaInscripcions;
    }
   
    public Byte getIdModalidad() {
        return this.idModalidad;
    }
    
    public void setIdModalidad(Byte idModalidad) {
        this.idModalidad = idModalidad;
    }
    public String getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }
    public Set getFichaInscripcions() {
        return this.fichaInscripcions;
    }
    
    public void setFichaInscripcions(Set fichaInscripcions) {
        this.fichaInscripcions = fichaInscripcions;
    }




}


