package com.cosettur.models.pojos;
// Generated 25/09/2018 11:20:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FichaInscripcion generated by hbm2java
 */
public class FichaInscripcion  implements java.io.Serializable {


     private Integer folio;
     private CatalogoCiclo catalogoCiclo;
     private CatalogoGrado catalogoGrado;
     private CatalogoModalidad catalogoModalidad;
     private CatalogoRuta catalogoRuta;
     private Usuario usuario;
     private byte semestre;
     private String localidad;
     private String tutor;
     private String tutorado;
     private String telefonoCasa;
     private Date fecha;
     private long pago;
     private Horario horario;

    public FichaInscripcion() {
    }

	
    public FichaInscripcion(CatalogoCiclo catalogoCiclo, CatalogoGrado catalogoGrado, CatalogoModalidad catalogoModalidad, CatalogoRuta catalogoRuta, Usuario usuario, byte semestre, String localidad, String tutor, String tutorado, String telefonoCasa, Date fecha, long pago) {
        this.catalogoCiclo = catalogoCiclo;
        this.catalogoGrado = catalogoGrado;
        this.catalogoModalidad = catalogoModalidad;
        this.catalogoRuta = catalogoRuta;
        this.usuario = usuario;
        this.semestre = semestre;
        this.localidad = localidad;
        this.tutor = tutor;
        this.tutorado = tutorado;
        this.telefonoCasa = telefonoCasa;
        this.fecha = fecha;
        this.pago = pago;
    }
    public FichaInscripcion(CatalogoCiclo catalogoCiclo, CatalogoGrado catalogoGrado, CatalogoModalidad catalogoModalidad, CatalogoRuta catalogoRuta, Usuario usuario, byte semestre, String localidad, String tutor, String tutorado, String telefonoCasa, Date fecha, long pago, Horario horario) {
       this.catalogoCiclo = catalogoCiclo;
       this.catalogoGrado = catalogoGrado;
       this.catalogoModalidad = catalogoModalidad;
       this.catalogoRuta = catalogoRuta;
       this.usuario = usuario;
       this.semestre = semestre;
       this.localidad = localidad;
       this.tutor = tutor;
       this.tutorado = tutorado;
       this.telefonoCasa = telefonoCasa;
       this.fecha = fecha;
       this.pago = pago;
       this.horario = horario;
    }
   
    public Integer getFolio() {
        return this.folio;
    }
    
    public void setFolio(Integer folio) {
        this.folio = folio;
    }
    public CatalogoCiclo getCatalogoCiclo() {
        return this.catalogoCiclo;
    }
    
    public void setCatalogoCiclo(CatalogoCiclo catalogoCiclo) {
        this.catalogoCiclo = catalogoCiclo;
    }
    public CatalogoGrado getCatalogoGrado() {
        return this.catalogoGrado;
    }
    
    public void setCatalogoGrado(CatalogoGrado catalogoGrado) {
        this.catalogoGrado = catalogoGrado;
    }
    public CatalogoModalidad getCatalogoModalidad() {
        return this.catalogoModalidad;
    }
    
    public void setCatalogoModalidad(CatalogoModalidad catalogoModalidad) {
        this.catalogoModalidad = catalogoModalidad;
    }
    public CatalogoRuta getCatalogoRuta() {
        return this.catalogoRuta;
    }
    
    public void setCatalogoRuta(CatalogoRuta catalogoRuta) {
        this.catalogoRuta = catalogoRuta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public byte getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(byte semestre) {
        this.semestre = semestre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public String getTutorado() {
        return this.tutorado;
    }
    
    public void setTutorado(String tutorado) {
        this.tutorado = tutorado;
    }
    public String getTelefonoCasa() {
        return this.telefonoCasa;
    }
    
    public void setTelefonoCasa(String telefonoCasa) {
        this.telefonoCasa = telefonoCasa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getPago() {
        return this.pago;
    }
    
    public void setPago(long pago) {
        this.pago = pago;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }




}


