package com.cosettur.models.pojos;
// Generated 25/09/2018 11:20:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String nombre;
     private String pass;
     private String telefono;
     private String correo;
     private Set<FichaInscripcion> fichaInscripcions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String nombre, String pass, String telefono, String correo) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.pass = pass;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Usuario(String usuario, String nombre, String pass, String telefono, String correo, Set fichaInscripcions) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.pass = pass;
       this.telefono = telefono;
       this.correo = correo;
       this.fichaInscripcions = fichaInscripcions;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<FichaInscripcion> getFichaInscripcions() {
        return this.fichaInscripcions;
    }
    
    public void setFichaInscripcions(Set fichaInscripcions) {
        this.fichaInscripcions = fichaInscripcions;
    }




}


